apiVersion : apps/v1
kind: Deployment
metadata:
  name: techvishalazureks 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techvishalazureks
  template:
    metadata:
      labels:
        app: techvishalazureks 
    spec:
      containers:
        - name: techvishalazureks 
          image: acr4k8s123.azurecr.io/techvishalazureks
          ports:
          - containerPort: 80